name = "feedme-deployment-checklist"
compatibility_date = "2024-12-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "feedme-deployment-checklist-db"
database_id = "2cfc573e-912a-4ab5-b7cc-998ec9e89126"
